name: divent
description: "Divent - Your social calendar app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  table_calendar: ^3.0.9


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - images/
  uses-material-design: true
